version: "3"
services:
  openwhistleblowing:
    image: mcilibrizzi/owb:latest
    build: .
    container_name: openwhistleblowing 
    cap_add:
    - NET_ADMIN
    ports:
    - 8080:80
    - 443:443
    environment:
    - DISABLE_MAIL_NOTIFICATION=${DISABLE_MAIL_NOTIFICATION}
    - EXTERNAL_HOSTNAME=${EXTERNAL_HOSTNAME}
    - HOSTS=${HOSTS}
    volumes:
    - ./data/files:/var/owb/files
    - ./data/db:/var/owb/db
    - ./data/log:/var/owb/log

